<a href="https://colab.research.google.com/github/fedassembly/tensorflow-cert-prep/blob/main/00_TensorFlow_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
tf.__version__

'2.13.0'

Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [2]:
scalar = tf.constant(1)
vector = tf.constant([1, 2])
matrix = tf.constant([[1,2],[3,4]])
tensor = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])

Find the shape, rank and size of the tensors you created in 1.

In [3]:
def describe_(x):
  x_name = [k for k, v in globals().items() if v is x][0]
  print(f"Shape of {x_name}: {x.shape}")
  print(f"Rank of {x_name}: {x.ndim}")
  print(f"Size of {x_name}: {tf.size(x).numpy()}")
  print("------------")

describe_(scalar)
describe_(vector)
describe_(matrix)
describe_(tensor)

Shape of scalar: ()
Rank of scalar: 0
Size of scalar: 1
------------
Shape of vector: (2,)
Rank of vector: 1
Size of vector: 2
------------
Shape of matrix: (2, 2)
Rank of matrix: 2
Size of matrix: 4
------------
Shape of tensor: (2, 2, 2)
Rank of tensor: 3
Size of tensor: 8
------------


Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [4]:
tf.random.set_seed(42)
A = tf.random.uniform(shape=[5, 300], minval=0., maxval=1.)
B = tf.random.uniform(shape=[5, 300], minval=0., maxval=1.)

Multiply the two tensors you created in 3 using matrix multiplication.

In [5]:
tf.matmul(A, B, transpose_b=True)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33345 , 73.40498 , 77.159615, 73.98369 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.08526 , 69.064064, 74.30776 , 72.27616 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.13417 ]],
      dtype=float32)>

Multiply the two tensors you created in 3 using dot product.

In [6]:
tf.tensordot(A, tf.transpose(B), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33345 , 73.40498 , 77.159615, 73.98369 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.08526 , 69.064064, 74.30776 , 72.27616 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.13417 ]],
      dtype=float32)>

Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [7]:
C = tf.random.uniform(shape=[224, 224, 3])

Find the min and max values of the tensor you created in 6



In [8]:
tf.reduce_min(C).numpy() ,tf.reduce_max(C).numpy()

(2.3841858e-07, 0.9999918)

Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [9]:
D = tf.random.uniform(shape=[1, 224, 224, 3])
tf.squeeze(D).shape

TensorShape([224, 224, 3])

Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [10]:
E = tf.constant([1,1,1,0,0,0,2,2,4,3])
assert tf.argmax(E).numpy() == 8


One-hot encode the tensor you created in 9.

In [11]:
tf.one_hot(E, depth=tf.size(tf.unique(E).y).numpy())

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.]], dtype=float32)>